export const AUDIT_ENTITY = {
  OTP_TOKEN: "OTP_TOKEN",
  USER: "USER",
  ROLE: "ROLE",
  ROLE_PERMISSION: "ROLE_PERMISSION",
  USER_ROLE: "USER_ROLE",
  EMAIL_DOMAIN: "EMAIL_DOMAIN",
  PR: "PR",
  AUTH_SESSION: "AUTH_SESSION",
  RELEASE: "RELEASE",
  RELEASE_PR_MAP: "RELEASE_PR_MAP",
  RELEASE_NOTE: "RELEASE_NOTE"
} as const;

export const AUDIT_ACTION = {
  AUTH_OTP_REQUESTED: "AUTH_OTP_REQUESTED",
  AUTH_OTP_EXPIRED: "AUTH_OTP_EXPIRED",
  AUTH_OTP_CONSUMED: "AUTH_OTP_CONSUMED",
  AUTH_USER_CREATED: "AUTH_USER_CREATED",
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGOUT_CURRENT_SESSION: "AUTH_LOGOUT_CURRENT_SESSION",
  AUTH_LOGOUT_ALL_SESSIONS: "AUTH_LOGOUT_ALL_SESSIONS",
  PROFILE_UPDATED: "PROFILE_UPDATED",
  PROFILE_VERIFICATION_REQUIRED: "PROFILE_VERIFICATION_REQUIRED",
  USER_CREATED: "USER_CREATED",
  USER_APPROVED: "USER_APPROVED",
  USER_DISAPPROVED: "USER_DISAPPROVED",
  USER_ROLE_ASSIGNED: "USER_ROLE_ASSIGNED",
  USER_ROLE_REMOVED: "USER_ROLE_REMOVED",
  ROLE_CREATED: "ROLE_CREATED",
  ROLE_UPDATED: "ROLE_UPDATED",
  ROLE_DELETED: "ROLE_DELETED",
  ROLE_PERMISSION_ASSIGNED: "ROLE_PERMISSION_ASSIGNED",
  ROLE_PERMISSION_REMOVED: "ROLE_PERMISSION_REMOVED",
  EMAIL_DOMAIN_CREATED: "EMAIL_DOMAIN_CREATED",
  EMAIL_DOMAIN_DELETED: "EMAIL_DOMAIN_DELETED",
  EMAIL_DOMAIN_STATUS_UPDATED: "EMAIL_DOMAIN_STATUS_UPDATED",
  PR_CREATED: "PR_CREATED",
  PR_STATUS_UPDATED: "PR_STATUS_UPDATED",
  PR_REASSIGNED: "PR_REASSIGNED",
  PR_RELEASE_MODE_UPDATED: "PR_RELEASE_MODE_UPDATED",
  RELEASE_CREATED: "RELEASE_CREATED",
  RELEASE_UPDATED: "RELEASE_UPDATED",
  RELEASE_DELETED: "RELEASE_DELETED",
  RELEASE_PR_ADDED: "RELEASE_PR_ADDED",
  RELEASE_PR_REMOVED: "RELEASE_PR_REMOVED",
  RELEASE_PR_AUTO_LINKED: "RELEASE_PR_AUTO_LINKED",
  RELEASE_DATE_SET: "RELEASE_DATE_SET",
  RELEASE_CUTOFF_UPDATED: "RELEASE_CUTOFF_UPDATED",
  RELEASE_STATUS_UPDATED: "RELEASE_STATUS_UPDATED",
  RELEASE_NOTE_GENERATED: "RELEASE_NOTE_GENERATED",
  RELEASE_NOTE_UPDATED: "RELEASE_NOTE_UPDATED"
} as const;

export const AUDIT_ERROR_MESSAGE = {
  SYSTEM_ACTOR_MISSING:
    "System audit actor not found. Run database seed before starting API writes."
} as const;

export type AuditEntity = (typeof AUDIT_ENTITY)[keyof typeof AUDIT_ENTITY];
export type AuditAction = (typeof AUDIT_ACTION)[keyof typeof AUDIT_ACTION];
