export const NOTIFICATION_EVENT = {
  PROFILE_VERIFICATION_REQUIRED: "PROFILE_VERIFICATION_REQUIRED",
  PR_ASSIGNED: "PR_ASSIGNED",
  PR_STATUS_UPDATED: "PR_STATUS_UPDATED",
  PR_SUBMITTED: "PR_SUBMITTED",
  RELEASE_CREATED: "RELEASE_CREATED",
  RELEASE_PR_AUTO_LINKED: "RELEASE_PR_AUTO_LINKED",
  RELEASE_NOTE_UPDATED: "RELEASE_NOTE_UPDATED"
} as const;

export type NotificationEvent = (typeof NOTIFICATION_EVENT)[keyof typeof NOTIFICATION_EVENT];
