export const PERMISSIONS = [
  "CAN_CREATE_PR",
  "CAN_VIEW_ALL_PRS",
  "CAN_REVIEW_PR",
  "CAN_ASSIGN_PR",
  "CAN_GENERATE_OWN_RELEASE_NOTES",
  "CAN_GENERATE_FULL_RELEASE_NOTES",
  "CAN_MANAGE_ROLES",
  "CAN_MANAGE_PERMISSIONS",
  "CAN_MANAGE_EMAIL_DOMAIN",
  "CAN_VERIFY_USERS",
  "CAN_CREATE_USER",
  "CAN_ASSIGN_ROLE",
  "CAN_MANAGE_RELEASE",
  "CAN_SET_PROD_RELEASE_DATE"
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number];
