export const API_BASE_PATH = "/api/v1";

export const ROUTE_PATH = {
  HEALTH: "/health",
  AUTH: "/auth",
  AUTH_REQUEST_OTP: "/request-otp",
  AUTH_VERIFY_OTP: "/verify-otp",
  AUTH_LOGOUT: "/logout",
  PROFILE: "/profile",
  PROFILE_ROOT: "/",
  USERS: "/users",
  USERS_ROOT: "/",
  USERS_DIRECTORY: "/directory",
  USERS_APPROVE: "/:id/approve",
  USERS_DISAPPROVE: "/:id/disapprove",
  USERS_ASSIGN_ROLE: "/:id/roles",
  USERS_REMOVE_ROLE: "/:id/roles/:roleId",
  ROLES: "/roles",
  ROLES_ROOT: "/",
  ROLES_BY_ID: "/:id",
  ROLES_ASSIGN_PERMISSION: "/:id/permissions",
  ROLES_REMOVE_PERMISSION: "/:id/permissions/:permissionId",
  EMAIL_DOMAINS: "/email-domains",
  EMAIL_DOMAINS_ROOT: "/",
  EMAIL_DOMAINS_BY_ID: "/:id",
  EMAIL_DOMAINS_UPDATE_STATUS: "/:id/status",
  PRS: "/prs",
  PRS_ROOT: "/",
  PRS_UPDATE_STATUS: "/:id/status",
  PRS_ASSIGN: "/:id/assign",
  PRS_UPDATE_RELEASE_MODE: "/release-mode",
  RELEASES: "/releases",
  RELEASES_ROOT: "/",
  RELEASES_DETAIL: "/:id",
  RELEASES_BY_ID: "/:id",
  RELEASES_ADD_PR: "/:id/add-pr",
  RELEASES_REMOVE_PR: "/:id/remove-pr",
  RELEASES_UPDATE: "/:id",
  RELEASES_UPDATE_DATE: "/:id/date",
  RELEASE_NOTES: "/release-notes",
  RELEASE_NOTES_MY: "/my",
  RELEASE_NOTES_BY_RELEASE: "/:releaseId",
  AUDIT_LOGS: "/audit-logs",
  AUDIT_LOGS_ROOT: "/",
  NOTIFICATIONS: "/notifications",
  NOTIFICATIONS_ROOT: "/"
} as const;
